config/routes.rb
Rails.application.routes.draw do
  root to: "orders#index"

  get '/', to: "orders#index"
  post '/update-status', to: 'orders#update_status'
  get '/artwork/:id', to: 'orders#order_artwork', as: 'artwork'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
require_relative '../realhub/realhub_api.rb'

class OrdersController < ApplicationController
  def index
    # creates a formatted hash to be rendered
    rha = RealHubApi.new
    @status_options = rha.get_status_options
    @orders_hash = rha.create_orders_hash(rha.order_api_call)
  end

  # When you click the download artwork button on the view this function will trigger downloading the artwork
  def order_artwork
    order_item_response = RestClient.get("https://www.realhubapp.com/api/v2/order_items/#{params[:id]}.json?include_order_item_artwork=true", header={ 'x-api-token': ENV['API_KEY'], "User-Agent": "KierynChallenge" })
    order_item_hash = JSON.parse(order_item_response.body)
    #if there is no artwork then the function will return nil
    order_item_hash['artwork'] == nil ? nil : redirect_to(order_item_hash['artwork']['links']['download_url'])
  end

  # # Updates the status_id on the api server and then updates our orders_hash.
  # # Not currently functional as I can't get the params from the server-side JS
  # def update_status

  #   #change the status on the api server
  #   status_response = RestClient.put("https://www.realhubapp.com/api/v2/order_items/#{params[:item_id]}.json", {:status => "#{params[:new_status]}"}, header={ 'x-api-token': ENV['API_KEY'], "User-Agent": "KierynChallenge" } )
  #   status_hash = JSON.parse(status_response.body)
  #   #TODO - future features
  #   #check response from Api is valid otherwise raise error
  #   #render the page with the updated status associated with that item
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestRealhub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class='container'>
  <div class='navbar'>
    <h2 class="title">Orders</h2>
  </div>

  <% @orders_hash.each do |order| %>
    <div class='card'>
      <div class='card-header'>
        <p><%= "#{order[1][:agency_name]} - #{order[1][:address]}"%></p>
      </div>
      <% order[1][:items].each do |item| %>
        <div class='card-body'>
          <p><%= "#{item[:quantity]} x #{item[:name]}/#{item[:finish]}" %></p>
          <div class ='right-side-card-body'>
            <%= link_to "Download Artwork", artwork_path(item[:id]), class: "right-side-items downloadBtn", id:"artwork-btn"%>
            <p class='separator'> | </p>
            <p class="status-btn" data-item=<%= "#{item[:id]}" %>>Change Status</p>
            <p class='separator'> | </p>
            <div <%= raw "id='#{item[:status]}-color-parent'" %>>
              <p <%= raw "id='#{item[:status]}-color'" %>><%= "#{item[:status]}" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="modal">
    <div class='modal-content'>
      <div class='navbar'>
        <h3>Update status</h3>
      </div>
      <div class="modal-body">
        <form>
          <% @status_options.each do |status| %>
            <div class="status-option">
              <input type='radio' <%= raw "id='#{status.last}'" %> name="result" <%= raw "value='#{status.last}'" %> checked>
              <label <%= raw "for='#{status.last}'" %>><%= status.last %></label>
            </div>
          <% end %>
          <input type="submit" id='save-button'>
        </form>
      </div>
    </div>
  </div>
</div>